import fs from 'fs/promises';
import path from 'path';

/**
 * Handles the creation of new project directories and basic file structures for generated apps.
 */
class ProjectScaffolder {
    /**
     * Creates an instance of ProjectScaffolder.
     * @param {string} outputDirectory The base directory where the new project will be created.
     * @param {string} projectName The name of the new project. This will also be the root directory name.
     */
    constructor(outputDirectory, projectName) {
        if (!outputDirectory || typeof outputDirectory !== 'string') {
            throw new Error("Invalid outputDirectory: Must be a non-empty string.");
        }
        if (!projectName || typeof projectName !== 'string') {
            throw new Error("Invalid projectName: Must be a non-empty string.");
        }

        this.projectRoot = path.join(outputDirectory, projectName);
        this.projectName = projectName;
        this.normalizedProjectName = projectName.toLowerCase().replace(/\s+/g, '-');
    }

    /**
     * Creates a directory, recursively if needed.
     * @param {string} dirPath The full path to the directory to create.
     * @returns {Promise<void>}
     * @private
     */
    async _createDirectory(dirPath) {
        try {
            await fs.mkdir(dirPath, { recursive: true });
            // console.log(`Created directory: ${dirPath}`); // Uncomment for detailed logging
        } catch (error) {
            console.error(`Error creating directory ${dirPath}:`, error.message);
            throw new Error(`Failed to create directory '${dirPath}': ${error.message}`);
        }
    }

    /**
     * Creates a file with the given content.
     * @param {string} filePath The full path to the file to create.
     * @param {string} content The content to write to the file.
     * @returns {Promise<void>}
     * @private
     */
    async _createFile(filePath, content) {
        try {
            await fs.writeFile(filePath, content, 'utf8');
            // console.log(`Created file: ${filePath}`); // Uncomment for detailed logging
        } catch (error) {
            console.error(`Error creating file ${filePath}:`, error.message);
            throw new Error(`Failed to create file '${filePath}': ${error.message}`);
        }
    }

    /**
     * Generates the content for a basic `package.json` file.
     * @returns {string} The JSON string for `package.json`.
     * @private
     */
    _generatePackageJsonContent() {
        return JSON.stringify({
            name: this.normalizedProjectName,
            version: '1.0.0',
            description: `A new application generated by AppGen: ${this.projectName}.`,
            main: 'src/index.js',
            scripts: {
                start: 'node src/index.js',
                test: 'echo "Error: no test specified" && exit 1'
            },
            keywords: [this.normalizedProjectName, 'appgen', 'generated-app'],
            author: 'AppGen',
            license: 'MIT',
            dependencies: {},
            devDependencies: {}
        }, null, 2);
    }

    /**
     * Generates the content for a basic `README.md` file.
     * @returns {string} The content for `README.md`.
     * @private
     */
    _generateReadmeContent() {
        return `# ${this.projectName}\n\nThis is a new application generated by AppGen.\n\n## Getting Started\n\nTo run this application, navigate to the project root and execute:\n\n\`\`\`bash\nnpm install\nnpm start\n\`\`\`\n`;
    }

    /**
     * Generates the content for a basic `.gitignore` file.
     * @returns {string} The content for `.gitignore`.
     * @private
     */
    _generateGitignoreContent() {
        return `node_modules/\n.env\nbuild/\ndist/\n*.log\n`;
    }

    /**
     * Generates the content for a basic `src/index.js` file.
     * @returns {string} The content for `index.js`.
     * @private
     */
    _generateIndexJsContent() {
        return `/**
 * Main entry point for the ${this.projectName} application.
 * Generated by AppGen.
 */
console.log('Hello from ${this.projectName}!');
console.log('This is a basic application scaffolded by AppGen. Start building your app!');
`;
    }

    /**
     * Generates the content for a basic `public/index.html` file.
     * @returns {string} The content for `index.html`.
     * @private
     */
    _generatePublicHtmlContent() {
        return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${this.projectName}</title>
    <style>
        body { font-family: sans-serif; margin: 2em; background-color: #f4f4f4; color: #333; }
        h1 { color: #0056b3; }
        p { line-height: 1.5; }
    </style>
</head>
<body>
    <h1>Welcome to ${this.projectName}!</h1>
    <p>This is a basic HTML file generated by AppGen.</p>
    <p>You can find the main JavaScript entry point in <code>src/index.js</code>.</p>
    
    <script src="../src/index.js"></script>
</body>
</html>
`;
    }

    /**
     * Scaffolds the new project by creating directories and basic files.
     * @returns {Promise<string>} A promise that resolves with the absolute path to the created project root.
     * @throws {Error} If any directory or file creation fails.
     */
    async scaffold() {
        console.log(`Starting to scaffold new project: "${this.projectName}" at "${this.projectRoot}"`);

        try {
            // 1. Create the root project directory
            await this._createDirectory(this.projectRoot);

            // 2. Create common subdirectories
            const srcDir = path.join(this.projectRoot, 'src');
            const publicDir = path.join(this.projectRoot, 'public');
            
            await this._createDirectory(srcDir);
            await this._createDirectory(publicDir);

            // 3. Create essential files in the root directory
            await this._createFile(
                path.join(this.projectRoot, 'package.json'),
                this._generatePackageJsonContent()
            );
            await this._createFile(
                path.join(this.projectRoot, 'README.md'),
                this._generateReadmeContent()
            );
            await this._createFile(
                path.join(this.projectRoot, '.gitignore'),
                this._generateGitignoreContent()
            );

            // 4. Create basic files in subdirectories
            await this._createFile(
                path.join(srcDir, 'index.js'),
                this._generateIndexJsContent()
            );
            await this._createFile(
                path.join(publicDir, 'index.html'),
                this._generatePublicHtmlContent()
            );

            console.log(`Successfully scaffolded project: "${this.projectName}" at "${this.projectRoot}"`);
            return this.projectRoot;
        } catch (error) {
            console.error(`Scaffolding failed for project "${this.projectName}":`, error.message);
            throw error; // Re-throw the error after logging
        }
    }
}

export default ProjectScaffolder;